# Generated by Django 3.2.25 on 2024-07-30 08:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0003_auto_20240730_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='image.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='content',
            new_name='front_content',
        ),
        migrations.AddField(
            model_name='skills',
            name='back_content',
            field=models.CharField(default='things', max_length=100),
            preserve_default=False,
        ),
    ]
