# Generated by Django 3.2.25 on 2024-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0004_auto_20240730_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
    ]
