# Generated by Django 3.2.25 on 2024-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0006_article_comment_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
