# Generated by Django 3.2.25 on 2024-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
