# Generated by Django 3.2.25 on 2024-08-10 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0009_certificate_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='criteria',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='platorm',
            field=models.CharField(default='someting', max_length=100),
            preserve_default=False,
        ),
    ]
