# Generated by Django 4.2.5 on 2024-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0015_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('webdev', 'webdev'), ('appdev', 'appdev'), ('graphic', 'graphic'), ('mlai', 'mlai'), ('iot', 'iot')], default='web dev', max_length=100),
        ),
    ]
