# Generated by Django 4.2.5 on 2025-04-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0017_alter_projects_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='type',
        ),
    ]
