# Generated by Django 4.2.5 on 2025-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0019_project_delete_projects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Languages",
            new_name="Skill",
        ),
        migrations.RenameModel(
            old_name="Skills",
            new_name="Service",
        ),
    ]
