# Generated by Django 4.2.5 on 2025-07-28 07:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0020_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('webdev', 'Web Dev'), ('appdev', 'App Dev'), ('graphic', 'Graphics'), ('mlai', 'ML/AI'), ('iot', 'IoT')], default='webdev', max_length=100),
        ),
    ]
