# Generated by Django 4.2.5 on 2025-07-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0021_alter_project_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Expertise',
        ),
        migrations.AlterModelTable(
            name='expertise',
            table='viir_folio_service',
        ),
    ]
