# Generated by Django 4.2.5 on 2025-07-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0022_rename_service_expertise_alter_expertise_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
    ]
