# Generated by Django 4.2.5 on 2025-07-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0023_remove_project_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='topic',
        ),
    ]
