# Generated by Django 6.0.2 on 2026-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0027_remove_about_age_about_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-start_date"], "verbose_name_plural": "Education"},
        ),
        migrations.RemoveField(
            model_name="education",
            name="date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="rank",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.IntegerField(default=2024, help_text="End year (YYYY)"),
        ),
        migrations.AddField(
            model_name="education",
            name="institute_name",
            field=models.CharField(
                default="", help_text="Name of institute/university", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.IntegerField(default=2020, help_text="Start year (YYYY)"),
        ),
        migrations.AlterField(
            model_name="education",
            name="subject",
            field=models.CharField(
                default="", help_text="Subject/Field of study", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(
                default="", help_text="Degree/Qualification title", max_length=100
            ),
        ),
    ]
