# Generated by Django 6.0.2 on 2026-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0037_delete_expertise_alter_project_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='platorm',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default-blog-image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
