# Generated by Django 3.2.25 on 2026-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0042_sitesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="topic",
        ),
        migrations.AddField(
            model_name="about",
            name="hero_typed_text",
            field=models.CharField(
                default="Full-Stack Developer, Cyber Security, ML/AI, IoT",
                help_text="Comma-separated strings for the hero typing animation",
                max_length=500,
            ),
        ),
    ]
