# Generated by Django 3.2.25 on 2026-06-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0046_auto_20260611_0246"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="about",
            name="core_competencies",
        ),
        migrations.RemoveField(
            model_name="about",
            name="education_summary",
        ),
        migrations.RemoveField(
            model_name="about",
            name="experience_years",
        ),
    ]
