# Generated by Django 3.2.25 on 2026-06-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0047_auto_20260611_0255"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="certifications_count",
            field=models.IntegerField(
                default=0, help_text="Manual count of your certifications"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="current_focus",
            field=models.CharField(
                blank=True,
                help_text="e.g., Application Security • Threat Detection",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="open_to_work",
            field=models.BooleanField(
                default=True,
                help_text="Show the blinking green 'Open to Work' dot on your profile picture",
            ),
        ),
    ]
