# Generated by Django 3.2.25 on 2026-06-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0048_auto_20260611_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='projects_count',
            field=models.CharField(default='10+', help_text='e.g., 10+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='research_count',
            field=models.CharField(default='2+', help_text='e.g., 2+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='status_text',
            field=models.CharField(default='OPEN TO WORK', help_text='Text for the blinking status dot (e.g., OPEN TO WORK)', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='certifications_count',
            field=models.CharField(default='5+', help_text='e.g., 5+', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text='Show the blinking green status dot on your profile picture'),
        ),
    ]
