# Generated by Django 3.2.25 on 2026-06-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0053_auto_20260612_0045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="devto_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="hashnode_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="medium_url",
        ),
    ]
