# Generated by Django 3.2.25 on 2026-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0054_auto_20260612_0157"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo for the timeline circle",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
