# Generated by Django 3.2.25 on 2026-06-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0055_experience_company_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="company_logo",
        ),
    ]
