# Generated by Django 3.2.25 on 2026-06-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0056_remove_experience_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date']},
        ),
    ]
