# Generated by Django 3.2.25 on 2026-06-13 21:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0057_auto_20260614_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('webdev', 'Web Dev'), ('appdev', 'App Dev'), ('mlai', 'ML/AI'), ('iot', 'IoT')], default='webdev', max_length=100),
        ),
    ]
