# Generated by Django 3.2.25 on 2026-06-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0060_auto_20260615_0156"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logger",
        ),
    ]
