# Generated by Django 3.2.25 on 2026-07-05 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viir_folio', '0061_delete_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 5, 18, 35, 4, 720719, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
