# Generated by Django 4.2.30 on 2026-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viir_folio", "0064_auto_20260709_0034"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="inquiry_type",
            field=models.CharField(blank=True, default="General", max_length=50),
        ),
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
